name: "BuildCode"

on:
  push:
    branches: [ feat/docker_and_cleanup ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ feat/docker_and_cleanup ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/rwoloszyn/svxlink-build:latest
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build
        shell: bash
        run: |
          apt-get install nodejs npm
          mkdir -p svxlink/src/build
          cd svxlink/src/build
          cmake ..
          make
